services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mivita
      POSTGRES_PASSWORD: mivita_pass
      POSTGRES_DB: mivita_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
