"""add telegram_couriers

Revision ID: d27cddba88bb
Revises: 284f871c78ff
Create Date: 2026-05-26 10:59:38.457147+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27cddba88bb'
down_revision: Union[str, None] = '284f871c78ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('courier_id')
    )
    op.create_index(op.f('ix_telegram_couriers_id'), 'telegram_couriers', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_couriers_telegram_chat_id'), 'telegram_couriers', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_couriers_telegram_chat_id'), table_name='telegram_couriers')
    op.drop_index(op.f('ix_telegram_couriers_id'), table_name='telegram_couriers')
    op.drop_table('telegram_couriers')
    # ### end Alembic commands ###
